/**
 * AUTO-GENERATED by node scripts/goon-test.mjs — do not edit by hand.
 * Re-run a goon test to refresh scores after adding/fixing sources.
 */

export type PlaybackEnvScore = "browser" | "extension";
export type MediaBucketScore = "movie" | "show" | "anime";

export type SourceBucketStats = {
  /** Hit rate 0–100 */
  hit: number;
  /** Median scrape+validate ms on hits (embed-only hits include a hop penalty) */
  hitMs: number;
  /** Ranking score: hit-rate / expected try cost. Higher = try sooner. */
  score: number;
};

export type SourceScoreMatrix = {
  updatedAt: string;
  /** Sources that should only run for anime titles. */
  animeOnly: string[];
  /**
   * Per source → env → media bucket.
   * Legacy matrices may store a bare hit-rate number instead of SourceBucketStats.
   */
  scores: Record<
    string,
    Partial<
      Record<PlaybackEnvScore, Partial<Record<MediaBucketScore, SourceBucketStats | number>>>
    >
  >;
};

export const SOURCE_SCORE_MATRIX: SourceScoreMatrix = {
  "updatedAt": "2026-08-31T03:58:42.108Z",
  "animeOnly": [
    "tqq",
    "myanime",
    "anidap"
  ],
  "scores": {
    "debrid": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "vidlink": {
      "browser": {
        "movie": {
          "hit": 77.8,
          "hitMs": 568,
          "score": 1368
        },
        "anime": {
          "hit": 33.3,
          "hitMs": 349,
          "score": 1434
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 77.8,
          "hitMs": 361,
          "score": 1876
        },
        "anime": {
          "hit": 33.3,
          "hitMs": 345,
          "score": 662
        },
        "show": {
          "hit": 50,
          "hitMs": 352,
          "score": 1792
        }
      }
    },
    "tqq": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 100,
          "hitMs": 2000,
          "score": 500
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 100,
          "hitMs": 2000,
          "score": 500
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "oneembed": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "fsonline": {
      "browser": {
        "movie": {
          "hit": 88.9,
          "hitMs": 2706,
          "score": 357
        },
        "anime": {
          "hit": 66.7,
          "hitMs": 2542,
          "score": 360
        },
        "show": {
          "hit": 100,
          "hitMs": 3273,
          "score": 306
        }
      },
      "extension": {
        "movie": {
          "hit": 88.9,
          "hitMs": 2515,
          "score": 389
        },
        "anime": {
          "hit": 66.7,
          "hitMs": 2511,
          "score": 375
        },
        "show": {
          "hit": 100,
          "hitMs": 2792,
          "score": 358
        }
      }
    },
    "cornclick": {
      "browser": {
        "movie": {
          "hit": 100,
          "hitMs": 4635,
          "score": 216
        },
        "anime": {
          "hit": 100,
          "hitMs": 1907,
          "score": 524
        },
        "show": {
          "hit": 100,
          "hitMs": 3068,
          "score": 326
        }
      },
      "extension": {
        "movie": {
          "hit": 100,
          "hitMs": 3031,
          "score": 330
        },
        "anime": {
          "hit": 100,
          "hitMs": 1266,
          "score": 790
        },
        "show": {
          "hit": 100,
          "hitMs": 2250,
          "score": 444
        }
      }
    },
    "sevenmovies": {
      "browser": {
        "movie": {
          "hit": 100,
          "hitMs": 4510,
          "score": 222
        },
        "anime": {
          "hit": 100,
          "hitMs": 5255,
          "score": 190
        },
        "show": {
          "hit": 100,
          "hitMs": 2523,
          "score": 396
        }
      },
      "extension": {
        "movie": {
          "hit": 100,
          "hitMs": 3947,
          "score": 253
        },
        "anime": {
          "hit": 100,
          "hitMs": 4057,
          "score": 246
        },
        "show": {
          "hit": 100,
          "hitMs": 2814,
          "score": 355
        }
      }
    },
    "nova": {
      "browser": {
        "movie": {
          "hit": 88.9,
          "hitMs": 1339,
          "score": 638
        },
        "show": {
          "hit": 50,
          "hitMs": 2819,
          "score": 300
        },
        "anime": {
          "hit": 100,
          "hitMs": 3373,
          "score": 296
        }
      },
      "extension": {
        "movie": {
          "hit": 88.9,
          "hitMs": 1227,
          "score": 761
        },
        "anime": {
          "hit": 33.3,
          "hitMs": 1746,
          "score": 372
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "cuevana3": {
      "browser": {
        "movie": {
          "hit": 44.4,
          "hitMs": 4117,
          "score": 196
        },
        "anime": {
          "hit": 66.7,
          "hitMs": 5103,
          "score": 184
        },
        "show": {
          "hit": 100,
          "hitMs": 3301,
          "score": 303
        }
      },
      "extension": {
        "movie": {
          "hit": 44.4,
          "hitMs": 2566,
          "score": 330
        },
        "anime": {
          "hit": 66.7,
          "hitMs": 2816,
          "score": 332
        },
        "show": {
          "hit": 100,
          "hitMs": 2385,
          "score": 419
        }
      }
    },
    "vixsrc": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "anidap": {
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "cinehdplus": {
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    }
  }
};
