/**
 * Context-aware source ordering driven by goon-test statistics.
 *
 * Playback env: browser (no extension) | extension | desktop
 * Media bucket: movie | show | anime
 *
 * Matrix is regenerated by `node scripts/goon-test.mjs` (see goon-test skill).
 */

import { isExtensionActiveCached } from "@/backend/extension/messaging";
import {
  AnimeDetectionInput,
  ANIME_SOURCE_IDS,
  hasAnimeDetectionData,
  isAnimeSourceId,
  isAnimeTitle,
} from "@/utils/media/anime";
import {
  SOURCE_SCORE_MATRIX,
  SourceBucketStats,
  SourceScoreMatrix,
} from "@/utils/media/sourcePerformance.generated";

export type PlaybackEnv = "browser" | "extension" | "desktop";
export type MediaBucket = "movie" | "show" | "anime";

export type SourceOrderContext = {
  env: PlaybackEnv;
  mediaType: "movie" | "show";
  meta?: AnimeDetectionInput | null;
};

// Keep this aligned with the provider runner's parallel source race. Reserve
// one slot for a newly-added source that has not reached the goon matrix yet,
// otherwise a slow scored source can prevent the new source from ever starting.
const INITIAL_SOURCE_RACE_SIZE = 4;

/** Boost sources that only activate when the user has configured them. */
export function prioritizeConfiguredSources(
  ids: string[],
  opts: { hasDebridToken?: boolean },
): string[] {
  let out = [...ids];
  if (!opts.hasDebridToken) {
    return out.filter((id) => id !== "debrid");
  }
  if (out.includes("debrid")) {
    out = ["debrid", ...out.filter((id) => id !== "debrid")];
  }
  return out;
}

/** Drop token-gated sources from a sourcerer list (manual source picker, etc.). */
export function filterConfiguredSources<T extends { id: string }>(
  sources: T[],
  opts: { hasDebridToken?: boolean },
): T[] {
  if (opts.hasDebridToken) return sources;
  return sources.filter((s) => s.id !== "debrid");
}

export function detectPlaybackEnv(): PlaybackEnv {
  if (
    typeof window !== "undefined" &&
    (window.__PSTREAM_DESKTOP__ || window.__KSTREAM_DESKTOP_IPC__)
  ) {
    return "desktop";
  }
  if (isExtensionActiveCached()) return "extension";
  return "browser";
}

/** Resolve movie/show/anime bucket for scrape ordering. */
export function getMediaBucket(
  mediaType: "movie" | "show",
  meta?: AnimeDetectionInput | null,
): MediaBucket {
  if (isAnimeTitle(meta)) return "anime";
  if (mediaType === "show") return "show";
  return "movie";
}

function rankValue(
  stat: SourceBucketStats | number | null | undefined,
): number | null {
  if (stat == null) return null;
  if (typeof stat === "number") return stat;
  if (typeof stat.score === "number") return stat.score;
  if (typeof stat.hit === "number") return stat.hit;
  return null;
}

function scoreFor(
  matrix: SourceScoreMatrix,
  sourceId: string,
  env: PlaybackEnv,
  bucket: MediaBucket,
): number | null {
  const byEnv = matrix.scores[sourceId];
  if (!byEnv) return null;

  // Desktop ≈ extension capabilities (header injection / no CORS).
  const envKey: PlaybackEnv = env === "desktop" ? "extension" : env;
  const byBucket = byEnv[envKey] ?? byEnv.browser ?? byEnv.extension;
  if (!byBucket) return null;

  const direct = rankValue(byBucket[bucket]);
  if (direct != null) return direct;

  // Soft fallbacks so a show-specialist still ranks before unknowns on movies.
  if (bucket === "anime") {
    return rankValue(byBucket.show) ?? rankValue(byBucket.movie);
  }
  if (bucket === "show") {
    return rankValue(byBucket.movie);
  }
  return rankValue(byBucket.show);
}

/**
 * Order source ids for the current playback environment + title.
 * - Anime-only sources (TQQ, …) only appear on anime titles.
 * - Ranked by goon score (hit-rate / expected scrape+load time).
 * - On anime, specialists win remaining ties.
 * - Movies / shows: sort by that bucket’s score for the current env.
 * - Unknown sources keep relative input order when scores tie / are missing.
 */
export function orderSourceIdsForPlayback(
  sourceIds: string[],
  ctx: SourceOrderContext,
  matrix: SourceScoreMatrix = SOURCE_SCORE_MATRIX,
): string[] {
  const bucket = getMediaBucket(ctx.mediaType, ctx.meta);
  const animeOnly = new Set([
    ...ANIME_SOURCE_IDS,
    ...(matrix.animeOnly ?? []),
  ]);

  let pool = [...sourceIds];

  if (hasAnimeDetectionData(ctx.meta)) {
    if (bucket === "anime") {
      return sortByScore(pool, ctx.env, "anime", matrix, animeOnly);
    }
    pool = pool.filter((id) => !isAnimeSourceId(id) && !animeOnly.has(id));
  }

  return sortByScore(pool, ctx.env, bucket, matrix);
}

export function orderSourcesForPlayback<T extends { id: string }>(
  sources: T[],
  ctx: SourceOrderContext,
  matrix?: SourceScoreMatrix,
): T[] {
  const orderedIds = orderSourceIdsForPlayback(
    sources.map((s) => s.id),
    ctx,
    matrix,
  );
  const byId = new Map(sources.map((s) => [s.id, s]));
  return orderedIds
    .map((id) => byId.get(id))
    .filter((s): s is T => Boolean(s));
}

function sortByScore(
  ids: string[],
  env: PlaybackEnv,
  bucket: MediaBucket,
  matrix: SourceScoreMatrix,
  specialistIds?: Set<string>,
): string[] {
  const ordered = [...ids].sort((a, b) => {
    const sa = scoreFor(matrix, a, env, bucket);
    const sb = scoreFor(matrix, b, env, bucket);
    const na = sa == null ? -1 : sa;
    const nb = sb == null ? -1 : sb;
    if (nb !== na) return nb - na;
    // Same hit rate: anime specialists (TQQ) before general sources.
    if (specialistIds) {
      const specA = specialistIds.has(a) ? 1 : 0;
      const specB = specialistIds.has(b) ? 1 : 0;
      if (specB !== specA) return specB - specA;
    }
    // Stable-ish: keep original relative order when tied / missing.
    return ids.indexOf(a) - ids.indexOf(b);
  });

  const firstUnscored = ordered.findIndex(
    (id) => scoreFor(matrix, id, env, bucket) == null,
  );
  if (firstUnscored >= INITIAL_SOURCE_RACE_SIZE) {
    const [candidate] = ordered.splice(firstUnscored, 1);
    ordered.splice(INITIAL_SOURCE_RACE_SIZE - 1, 0, candidate);
  }

  return ordered;
}
