/**
 * AUTO-GENERATED by node scripts/goon-test.mjs — do not edit by hand.
 * Re-run a goon test to refresh scores after adding/fixing sources.
 */

export type PlaybackEnvScore = "browser" | "extension";
export type MediaBucketScore = "movie" | "show" | "anime";

export type SourceBucketStats = {
  /** Hit rate 0–100 */
  hit: number;
  /** Median scrape+validate ms on hits (embed-only hits include a hop penalty) */
  hitMs: number;
  /** Ranking score: hit-rate / expected try cost. Higher = try sooner. */
  score: number;
};

export type SourceScoreMatrix = {
  updatedAt: string;
  /** Sources that should only run for anime titles. */
  animeOnly: string[];
  /**
   * Per source → env → media bucket.
   * Legacy matrices may store a bare hit-rate number instead of SourceBucketStats.
   */
  scores: Record<
    string,
    Partial<
      Record<PlaybackEnvScore, Partial<Record<MediaBucketScore, SourceBucketStats | number>>>
    >
  >;
};

export const SOURCE_SCORE_MATRIX: SourceScoreMatrix = {
  "updatedAt": "2026-08-31T23:52:55.687Z",
  "animeOnly": [
    "tqq",
    "myanime",
    "anidap"
  ],
  "scores": {
    "debrid": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "vidlink": {
      "browser": {
        "movie": {
          "hit": 52.6,
          "hitMs": 386,
          "score": 1728
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 52.6,
          "hitMs": 384,
          "score": 1778
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "castletv": {
      "browser": {
        "movie": {
          "hit": 84.2,
          "hitMs": 1380,
          "score": 693
        },
        "anime": {
          "hit": 90.9,
          "hitMs": 1457,
          "score": 671
        },
        "show": {
          "hit": 100,
          "hitMs": 1474,
          "score": 678
        }
      },
      "extension": {
        "movie": {
          "hit": 84.2,
          "hitMs": 1377,
          "score": 697
        },
        "anime": {
          "hit": 90.9,
          "hitMs": 1294,
          "score": 755
        },
        "show": {
          "hit": 100,
          "hitMs": 1200,
          "score": 833
        }
      }
    },
    "tqq": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 100,
          "hitMs": 2000,
          "score": 500
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 100,
          "hitMs": 2000,
          "score": 500
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "fsonline": {
      "browser": {
        "movie": {
          "hit": 89.5,
          "hitMs": 2638,
          "score": 373
        },
        "anime": {
          "hit": 45.5,
          "hitMs": 2700,
          "score": 289
        },
        "show": {
          "hit": 100,
          "hitMs": 3011,
          "score": 332
        }
      },
      "extension": {
        "movie": {
          "hit": 89.5,
          "hitMs": 2510,
          "score": 393
        },
        "anime": {
          "hit": 45.5,
          "hitMs": 2529,
          "score": 307
        },
        "show": {
          "hit": 100,
          "hitMs": 2817,
          "score": 355
        }
      }
    },
    "cornclick": {
      "browser": {
        "movie": {
          "hit": 100,
          "hitMs": 5211,
          "score": 192
        },
        "anime": {
          "hit": 100,
          "hitMs": 1637,
          "score": 611
        },
        "show": {
          "hit": 91.7,
          "hitMs": 3629,
          "score": 210
        }
      },
      "extension": {
        "movie": {
          "hit": 100,
          "hitMs": 4029,
          "score": 248
        },
        "anime": {
          "hit": 100,
          "hitMs": 1090,
          "score": 917
        },
        "show": {
          "hit": 100,
          "hitMs": 2687,
          "score": 372
        }
      }
    },
    "sevenmovies": {
      "browser": {
        "movie": {
          "hit": 100,
          "hitMs": 4990,
          "score": 200
        },
        "anime": {
          "hit": 63.6,
          "hitMs": 3842,
          "score": 253
        },
        "show": {
          "hit": 100,
          "hitMs": 3026,
          "score": 330
        }
      },
      "extension": {
        "movie": {
          "hit": 100,
          "hitMs": 4152,
          "score": 241
        },
        "anime": {
          "hit": 45.5,
          "hitMs": 4001,
          "score": 228
        },
        "show": {
          "hit": 100,
          "hitMs": 3727,
          "score": 268
        }
      }
    },
    "way2movies": {
      "browser": {
        "movie": {
          "hit": 85,
          "hitMs": 2800,
          "score": 305
        },
        "anime": {
          "hit": 70,
          "hitMs": 3200,
          "score": 220
        },
        "show": {
          "hit": 90,
          "hitMs": 2500,
          "score": 360
        }
      },
      "extension": {
        "movie": {
          "hit": 88,
          "hitMs": 2600,
          "score": 338
        },
        "anime": {
          "hit": 75,
          "hitMs": 3000,
          "score": 250
        },
        "show": {
          "hit": 92,
          "hitMs": 2400,
          "score": 383
        }
      }
    },
    "nova": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 57.9,
          "hitMs": 1063,
          "score": 912
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "cuevana3": {
      "browser": {
        "movie": {
          "hit": 36.8,
          "hitMs": 4089,
          "score": 185
        },
        "anime": {
          "hit": 63.6,
          "hitMs": 3707,
          "score": 240
        },
        "show": {
          "hit": 83.3,
          "hitMs": 3591,
          "score": 254
        }
      },
      "extension": {
        "movie": {
          "hit": 36.8,
          "hitMs": 2893,
          "score": 284
        },
        "anime": {
          "hit": 63.6,
          "hitMs": 2526,
          "score": 368
        },
        "show": {
          "hit": 83.3,
          "hitMs": 2378,
          "score": 409
        }
      }
    },
    "vixsrc": {
      "browser": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      },
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "primesrc": {
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "anidap": {
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    },
    "cinehdplus": {
      "extension": {
        "movie": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "anime": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        },
        "show": {
          "hit": 0,
          "hitMs": 0,
          "score": 0
        }
      }
    }
  }
};
