/**
 * AUTO-GENERATED by node scripts/goon-test.mjs — do not edit by hand.
 * Re-run a goon test to refresh scores after adding/fixing sources.
 */

export type PlaybackEnvScore = "browser" | "extension";
export type MediaBucketScore = "movie" | "show" | "anime";

export type SourceScoreMatrix = {
  updatedAt: string;
  /** Sources that should only run for anime titles. */
  animeOnly: string[];
  /**
   * Hit-rate 0–100 per source → env → media bucket.
   * Missing buckets mean insufficient samples.
   */
  scores: Record<
    string,
    Partial<
      Record<PlaybackEnvScore, Partial<Record<MediaBucketScore, number>>>
    >
  >;
};

export const SOURCE_SCORE_MATRIX: SourceScoreMatrix = {
  "updatedAt": "2026-08-11T23:45:58.629Z",
  "animeOnly": [
    "tqq",
    "myanime"
  ],
  "scores": {
    "tqq": {
      "browser": {
        "movie": 0,
        "anime": 100,
        "show": 0
      },
      "extension": {
        "movie": 0,
        "anime": 100,
        "show": 0
      }
    },
    "fsonline": {
      "browser": {
        "movie": 89.5,
        "anime": 45.5,
        "show": 100
      },
      "extension": {
        "movie": 89.5,
        "anime": 45.5,
        "show": 100
      }
    },
    "cuevana3": {
      "browser": {
        "movie": 36.8,
        "anime": 63.6,
        "show": 83.3
      },
      "extension": {
        "movie": 36.8,
        "anime": 63.6,
        "show": 83.3
      }
    },
    "reyna": {
      "browser": {
        "movie": 89.5,
        "anime": 90.9,
        "show": 91.7
      },
      "extension": {
        "movie": 89.5,
        "anime": 90.9,
        "show": 91.7
      }
    },
    "oneembed": {
      "browser": {
        "movie": 94.7,
        "anime": 100,
        "show": 100
      },
      "extension": {
        "movie": 94.7,
        "anime": 90.9,
        "show": 91.7
      }
    },
    "sevenmovies": {
      "browser": {
        "movie": 94.7,
        "anime": 27.3,
        "show": 50
      },
      "extension": {
        "movie": 68.4,
        "anime": 45.5,
        "show": 50
      }
    },
    "vidrock": {
      "extension": {
        "movie": 100,
        "anime": 100,
        "show": 100
      }
    },
    "pelisplushd": {
      "extension": {
        "movie": 15.8,
        "anime": 0,
        "show": 0
      }
    }
  }
};
